export default function ProductCard({ data }) {
  const printedAt = new Date().toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  })

  return (
    <div className="receipt-card">
      <div className="receipt-meta">
        <span>{data.category}</span>
        <span>{printedAt}</span>
      </div>

      <hr className="receipt-rule" />

      <p className="receipt-label">Title</p>
      <h3 className="receipt-title">{data.title}</h3>

      <p className="receipt-label">Description</p>
      <p className="receipt-description">{data.description}</p>

      <p className="receipt-label">Tags</p>
      <div className="receipt-tags">
        {data.tags.map((tag, i) => (
          <div className="row" key={tag}>
            <span>{String(i + 1).padStart(2, '0')}</span>
            <span>{tag}</span>
          </div>
        ))}
      </div>

      <div className="barcode" />
      <p className="receipt-footline">GENERATED BY GEMINI — TAGSHOP</p>
    </div>
  )
}
